os: linux
dist: xenial
language: shell

addons:
  apt:
    packages:
    - git
    - wget
    - libncurses-dev
    - flex
    - bison
    - gperf
    - python
    - python-pip
    - python-setuptools
    - python-serial
    - python-click
    - python-cryptography
    - python-future
    - python-pyparsing
    - python-pyelftools
    - cmake
    - ninja-build
    - ccache

install:
  - mkdir ~/esp
  - cd ~/esp
  - git clone -b release/v4.0 --recursive https://github.com/espressif/esp-idf.git
  - cd ~/esp/esp-idf
  - ./install.sh
  - . ~/esp/esp-idf/export.sh

script:
  - cd $TRAVIS_BUILD_DIR
  - mv defsdkconfig sdkconfig
  - make app

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Jody L. Whitlock"
  - git config --local user.email "jody.whitlock@nunya.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: $TRAVIS_BUILD_DIR/build/esp32-ota-example.bin
  skip_cleanup: true
  draft: true
