os: linux
dist: xenial
language: shell

addons:
  apt:
    packages:
    - git
    - wget
    - libncurses-dev
    - flex
    - bison
    - gperf
    - python
    - python-pip
    - python-setuptools
    - python-serial
    - python-click
    - python-cryptography
    - python-future
    - python-pyparsing
    - python-pyelftools
    - cmake
    - ninja-build
    - ccache

install:
  - mkdir ~/esp
  - cd ~/esp
  - git clone -b release/v4.0 --recursive https://github.com/espressif/esp-idf.git
  - cd ~/esp/esp-idf
  - ./install.sh
  - . ~/esp/esp-idf/export.sh

script:
  - cd $TRAVIS_BUILD_DIR
  - mv defsdkconfig sdkconfig
  - make app

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "builds@travis-ci.com"
  - git config --local user.email "Travis CI"
  - export TRAVIS_TAG=$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER
  - git tag $TRAVIS_TAG

deploy:
  - provider: releases
    token: $GITHUB_API_KEY
    file: $TRAVIS_BUILD_DIR/build/esp32-ota-example.bin
    cleanup: true
    overwrite: true
    prerelease: true
    on:
      condition: ($TRAVIS_BRANCH != master) AND ($TRAVIS_TAG =~ ^(\d+\.)?(\d+\.)?(\*|\d+)$)
      all_branches: true
  - provider: releases
    token: $GITHUB_API_KEY
    file: $TRAVIS_BUILD_DIR/build/esp32-ota-example.bin
    cleanup: true
    overwrite: true
    prerelease: true
    on:
      condition: ($TRAVIS_BRANCH = master) AND ($TRAVIS_TAG =~ ^(\d+\.)?(\d+\.)?(\*|\d+)$)
      all_branches: true
